# Generated by Django 4.1.13 on 2024-08-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0005_animalmodel_name_alter_animalmodel_outcome_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalmodel",
            name="age_upon_outcome_in_weeks",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="animalmodel",
            name="location_lat",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="animalmodel",
            name="location_long",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="animalmodel",
            name="outcome_type",
            field=models.CharField(max_length=100),
        ),
    ]
