# Generated by Django 5.1 on 2024-08-19 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0006_alter_animalmodel_age_upon_outcome_in_weeks_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnimalModel",
        ),
    ]
