# Generated by Django 5.1 on 2024-08-19 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0008_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnimalModel",
        ),
    ]
